// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Un frame YUV420 dalla camera Flutter. Vive solo il tempo dell'analisi:
/// il nativo non lo salva né lo inoltra (NFR1/NFR2).
class FramePacket {
  FramePacket({
    required this.width,
    required this.height,
    required this.rotationDegrees,
    required this.yPlane,
    required this.uPlane,
    required this.vPlane,
    required this.yRowStride,
    required this.uvRowStride,
    required this.uvPixelStride,
    required this.timestampMs,
  });

  int width;

  int height;

  /// Rotazione da applicare perché il frame risulti upright
  /// (sensorOrientation della camera frontale, tipicamente 270).
  int rotationDegrees;

  Uint8List yPlane;

  Uint8List uPlane;

  Uint8List vPlane;

  int yRowStride;

  int uvRowStride;

  int uvPixelStride;

  int timestampMs;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      rotationDegrees,
      yPlane,
      uPlane,
      vPlane,
      yRowStride,
      uvRowStride,
      uvPixelStride,
      timestampMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static FramePacket decode(Object result) {
    result as List<Object?>;
    return FramePacket(
      width: result[0]! as int,
      height: result[1]! as int,
      rotationDegrees: result[2]! as int,
      yPlane: result[3]! as Uint8List,
      uPlane: result[4]! as Uint8List,
      vPlane: result[5]! as Uint8List,
      yRowStride: result[6]! as int,
      uvRowStride: result[7]! as int,
      uvPixelStride: result[8]! as int,
      timestampMs: result[9]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FramePacket || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(rotationDegrees, other.rotationDegrees) && _deepEquals(yPlane, other.yPlane) && _deepEquals(uPlane, other.uPlane) && _deepEquals(vPlane, other.vPlane) && _deepEquals(yRowStride, other.yRowStride) && _deepEquals(uvRowStride, other.uvRowStride) && _deepEquals(uvPixelStride, other.uvPixelStride) && _deepEquals(timestampMs, other.timestampMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FramePacket(width: $width, height: $height, rotationDegrees: $rotationDegrees, yPlane: $yPlane, uPlane: $uPlane, vPlane: $vPlane, yRowStride: $yRowStride, uvRowStride: $uvRowStride, uvPixelStride: $uvPixelStride, timestampMs: $timestampMs)';
  }
}

/// Risultato dell'analisi: SOLO landmark e blendshapes, mai pixel.
class FrameAnalysis {
  FrameAnalysis({
    required this.faceDetected,
    required this.faceLandmarks,
    required this.blendshapes,
    required this.poseDetected,
    required this.poseLandmarks,
    required this.inferenceTimeMs,
    required this.timestampMs,
  });

  bool faceDetected;

  /// Coordinate normalizzate [x0, y0, x1, y1, ...] nello spazio del frame
  /// ruotato (478 punti → 956 valori); vuoto se nessun volto.
  List<double> faceLandmarks;

  /// Nome blendshape → score 0..1; vuoto se nessun volto.
  Map<String, double> blendshapes;

  bool poseDetected;

  /// Come [faceLandmarks], 33 punti → 66 valori; vuoto se nessuna posa.
  List<double> poseLandmarks;

  int inferenceTimeMs;

  int timestampMs;

  List<Object?> _toList() {
    return <Object?>[
      faceDetected,
      faceLandmarks,
      blendshapes,
      poseDetected,
      poseLandmarks,
      inferenceTimeMs,
      timestampMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static FrameAnalysis decode(Object result) {
    result as List<Object?>;
    return FrameAnalysis(
      faceDetected: result[0]! as bool,
      faceLandmarks: (result[1]! as List<Object?>).cast<double>(),
      blendshapes: (result[2]! as Map<Object?, Object?>).cast<String, double>(),
      poseDetected: result[3]! as bool,
      poseLandmarks: (result[4]! as List<Object?>).cast<double>(),
      inferenceTimeMs: result[5]! as int,
      timestampMs: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FrameAnalysis || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(faceDetected, other.faceDetected) && _deepEquals(faceLandmarks, other.faceLandmarks) && _deepEquals(blendshapes, other.blendshapes) && _deepEquals(poseDetected, other.poseDetected) && _deepEquals(poseLandmarks, other.poseLandmarks) && _deepEquals(inferenceTimeMs, other.inferenceTimeMs) && _deepEquals(timestampMs, other.timestampMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FrameAnalysis(faceDetected: $faceDetected, faceLandmarks: $faceLandmarks, blendshapes: $blendshapes, poseDetected: $poseDetected, poseLandmarks: $poseLandmarks, inferenceTimeMs: $inferenceTimeMs, timestampMs: $timestampMs)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is FramePacket) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is FrameAnalysis) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return FramePacket.decode(readValue(buffer)!);
      case 130:
        return FrameAnalysis.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SensingHostApi {
  /// Constructor for [SensingHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SensingHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Carica i modelli MediaPipe dagli asset. Idempotente.
  Future<void> initialize() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mindbridge.SensingHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Analizza un frame. Ritorna null se il landmarker non è pronto.
  /// Gira su thread in background per non bloccare la UI nativa.
  Future<FrameAnalysis?> analyzeFrame(FramePacket packet) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mindbridge.SensingHostApi.analyzeFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[packet]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as FrameAnalysis?;
  }

  /// Rilascia i landmarker.
  Future<void> close() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.mindbridge.SensingHostApi.close$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
