// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package it.unitn.mindbridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SensingApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Un frame YUV420 dalla camera Flutter. Vive solo il tempo dell'analisi:
 * il nativo non lo salva né lo inoltra (NFR1/NFR2).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FramePacket (
  val width: Long,
  val height: Long,
  /**
   * Rotazione da applicare perché il frame risulti upright
   * (sensorOrientation della camera frontale, tipicamente 270).
   */
  val rotationDegrees: Long,
  val yPlane: ByteArray,
  val uPlane: ByteArray,
  val vPlane: ByteArray,
  val yRowStride: Long,
  val uvRowStride: Long,
  val uvPixelStride: Long,
  val timestampMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FramePacket {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val rotationDegrees = pigeonVar_list[2] as Long
      val yPlane = pigeonVar_list[3] as ByteArray
      val uPlane = pigeonVar_list[4] as ByteArray
      val vPlane = pigeonVar_list[5] as ByteArray
      val yRowStride = pigeonVar_list[6] as Long
      val uvRowStride = pigeonVar_list[7] as Long
      val uvPixelStride = pigeonVar_list[8] as Long
      val timestampMs = pigeonVar_list[9] as Long
      return FramePacket(width, height, rotationDegrees, yPlane, uPlane, vPlane, yRowStride, uvRowStride, uvPixelStride, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      rotationDegrees,
      yPlane,
      uPlane,
      vPlane,
      yRowStride,
      uvRowStride,
      uvPixelStride,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FramePacket
    return SensingApiPigeonUtils.deepEquals(this.width, other.width) && SensingApiPigeonUtils.deepEquals(this.height, other.height) && SensingApiPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && SensingApiPigeonUtils.deepEquals(this.yPlane, other.yPlane) && SensingApiPigeonUtils.deepEquals(this.uPlane, other.uPlane) && SensingApiPigeonUtils.deepEquals(this.vPlane, other.vPlane) && SensingApiPigeonUtils.deepEquals(this.yRowStride, other.yRowStride) && SensingApiPigeonUtils.deepEquals(this.uvRowStride, other.uvRowStride) && SensingApiPigeonUtils.deepEquals(this.uvPixelStride, other.uvPixelStride) && SensingApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.width)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.height)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.yPlane)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.uPlane)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.vPlane)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.yRowStride)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.uvRowStride)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.uvPixelStride)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.timestampMs)
    return result
  }
  override fun toString(): String {
    return "FramePacket(width=$width, height=$height, rotationDegrees=$rotationDegrees, yPlane=${yPlane.contentToString()}, uPlane=${uPlane.contentToString()}, vPlane=${vPlane.contentToString()}, yRowStride=$yRowStride, uvRowStride=$uvRowStride, uvPixelStride=$uvPixelStride, timestampMs=$timestampMs)"
  }
}

/**
 * Risultato dell'analisi: SOLO landmark e blendshapes, mai pixel.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FrameAnalysis (
  val faceDetected: Boolean,
  /**
   * Coordinate normalizzate [x0, y0, x1, y1, ...] nello spazio del frame
   * ruotato (478 punti → 956 valori); vuoto se nessun volto.
   */
  val faceLandmarks: List<Double>,
  /** Nome blendshape → score 0..1; vuoto se nessun volto. */
  val blendshapes: Map<String, Double>,
  val poseDetected: Boolean,
  /** Come [faceLandmarks], 33 punti → 66 valori; vuoto se nessuna posa. */
  val poseLandmarks: List<Double>,
  val inferenceTimeMs: Long,
  val timestampMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameAnalysis {
      val faceDetected = pigeonVar_list[0] as Boolean
      val faceLandmarks = pigeonVar_list[1] as List<Double>
      val blendshapes = pigeonVar_list[2] as Map<String, Double>
      val poseDetected = pigeonVar_list[3] as Boolean
      val poseLandmarks = pigeonVar_list[4] as List<Double>
      val inferenceTimeMs = pigeonVar_list[5] as Long
      val timestampMs = pigeonVar_list[6] as Long
      return FrameAnalysis(faceDetected, faceLandmarks, blendshapes, poseDetected, poseLandmarks, inferenceTimeMs, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      faceDetected,
      faceLandmarks,
      blendshapes,
      poseDetected,
      poseLandmarks,
      inferenceTimeMs,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FrameAnalysis
    return SensingApiPigeonUtils.deepEquals(this.faceDetected, other.faceDetected) && SensingApiPigeonUtils.deepEquals(this.faceLandmarks, other.faceLandmarks) && SensingApiPigeonUtils.deepEquals(this.blendshapes, other.blendshapes) && SensingApiPigeonUtils.deepEquals(this.poseDetected, other.poseDetected) && SensingApiPigeonUtils.deepEquals(this.poseLandmarks, other.poseLandmarks) && SensingApiPigeonUtils.deepEquals(this.inferenceTimeMs, other.inferenceTimeMs) && SensingApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.faceDetected)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.faceLandmarks)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.blendshapes)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.poseDetected)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.poseLandmarks)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.inferenceTimeMs)
    result = 31 * result + SensingApiPigeonUtils.deepHash(this.timestampMs)
    return result
  }
  override fun toString(): String {
    return "FrameAnalysis(faceDetected=$faceDetected, faceLandmarks=$faceLandmarks, blendshapes=$blendshapes, poseDetected=$poseDetected, poseLandmarks=$poseLandmarks, inferenceTimeMs=$inferenceTimeMs, timestampMs=$timestampMs)"
  }
}
private open class SensingApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FramePacket.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameAnalysis.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FramePacket -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is FrameAnalysis -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SensingHostApi {
  /** Carica i modelli MediaPipe dagli asset. Idempotente. */
  fun initialize()
  /**
   * Analizza un frame. Ritorna null se il landmarker non è pronto.
   * Gira su thread in background per non bloccare la UI nativa.
   */
  fun analyzeFrame(packet: FramePacket): FrameAnalysis?
  /** Rilascia i landmarker. */
  fun close()

  companion object {
    /** The codec used by SensingHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      SensingApiPigeonCodec()
    }
    /** Sets up an instance of `SensingHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SensingHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mindbridge.SensingHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initialize()
              listOf(null)
            } catch (exception: Throwable) {
              SensingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mindbridge.SensingHostApi.analyzeFrame$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packetArg = args[0] as FramePacket
            val wrapped: List<Any?> = try {
              listOf(api.analyzeFrame(packetArg))
            } catch (exception: Throwable) {
              SensingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mindbridge.SensingHostApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.close()
              listOf(null)
            } catch (exception: Throwable) {
              SensingApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
